releaseType: java-yoshi
bumpMinorPreMajor: true
extraFiles:
  - bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/config/BigtableVersionInfo.java
  - bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableHBaseVersion.java
handleGHRelease: true
branches:
  - branch: bigtable-1.x
    releaseType: java-yoshi
    bumpMinorPreMajor: true
    handleGHRelease: true
  - releaseType: java-lts
    bumpMinorPreMajor: true
    handleGHRelease: true
    branch: 1.20.0-sp
