package com.google.cloud.bigtable.hbase.adapters.filters;

import com.google.api.client.repackaged.com.google.common.base.Preconditions;
import com.google.common.base.Joiner;

import java.util.List;

/**
 * An exception thrown when attempting to adapt unsupported filters.
 */
public class UnsupportedFilterException extends UnsupportedOperationException {
  /**
   * serialVersionUID generated by eclipse.
   */
  private static final long serialVersionUID = -8737704632500918999L;
  private static Joiner STATUS_JOINER = Joiner.on(", ");
  private final List<FilterSupportStatus> filterSupportStatuses;

  public UnsupportedFilterException(List<FilterSupportStatus> filterSupportStatuses) {
    super(String.format(
        "Unsupported filters encountered: %s",
        STATUS_JOINER.join(filterSupportStatuses)));
    Preconditions.checkArgument(
        !filterSupportStatuses.isEmpty(), "Unsupported statuses should not be empty.");
    this.filterSupportStatuses = filterSupportStatuses;
  }

  /**
   * The failed FilterSupportStatus instances containing reason messages.
   */
  public List<FilterSupportStatus> getFilterSupportStatuses() {
    return filterSupportStatuses;
  }
}
