package com.google.cloud.bigtable.mapreduce;

import org.apache.hadoop.hbase.mapreduce.Export;
import org.apache.hadoop.util.ProgramDriver;

/**
 * TODO: Insert description here. (generated by sduskis)
 */
public class Driver {

  public static void main(String[] args) {
    ProgramDriver programDriver = new ProgramDriver();
    int exitCode = -1;
    try {
      programDriver.addClass("export-table", Export.class,
          "A map/reduce program that exports a table to a file.");
      programDriver.addClass("import-table", Import.class,
          "A map/reduce program that imports a table to a file.");
      programDriver.driver(args);
      exitCode = programDriver.run(args);
    } catch (Throwable e) {
      e.printStackTrace();
    }
    System.exit(exitCode);
  }
}
